Remove dependency on arrayvec
IronCoreLabs/recrypt-rs pull request #152
Opened 2021-04-09 21:57 UTC by giarc3

Would need to bump MSRV to 1.48 because of [this addition](https://github.com/rust-lang/rust/pull/76310/) to Rust. We could possibly make do with an implementation available start in 1.43, but it doesn't seem as clean. 

Open to opinions on if the bump to 1.48 is acceptable, or if we should make an attempt at the 1.43 version instead.

2021-04-09 22:13 UTC, clintfred commented
I think the PR description should mention the build changes. I think you are just using rust_cache?

2021-04-09 22:16 UTC, clintfred commented on src/internal/bytedecoder.rs
> -from_arrayvec_n! {32, 128, 384}
The only usage you converted was for 32 bytes. I wonder if there are downstream deps that are depending on the 128 and 384 version? Or perhaps no one cares about them?

Since these `From` impls are part of recrypt's public interface, we would need to bump the minor version.

2021-04-09 22:18 UTC, clintfred requested changes
We need a minor version bump and an updated changelog.

2021-04-09 22:35 UTC, clintfred commented on src/internal/bytedecoder.rs
> -from_arrayvec_n! {32, 128, 384}
I was wrong. I missed that this was in the `internal` module, so these `From` impls aren't public. I guess the 128 and 384 versions were never being used. Sorry for the confusion.

2021-04-09 22:43 UTC, giarc3 commented
> I think the PR description should mention the build changes. I think you are just using rust_cache?

I added a brief description of the CI changes. They were fairly minor.

2021-04-12 15:53 UTC, skeet70 approved these changes

2021-04-12 15:55 UTC, skeet70 commented
I think if we're bumping MSRV we should at least minor bump. Too easy for a patch version to break builds. We might want to make public policy about that.

2021-04-12 16:13 UTC, clintfred approved these changes

2021-04-12 16:13 UTC, giarc3 commented
> I think if we're bumping MSRV we should at least minor bump. Too easy for a patch version to break builds. We might want to make public policy about that.

You're 100% right. We do need a policy on that because we've been burned by it with our dependencies multiple times

2021-04-12 18:06 UTC, coltfred approved these changes

2021-04-12 18:06 UTC, coltfred commented on CHANGELOG.md
> +## 0.12.1 (Unreleased)
This version should be fixed to correctly point out that we're going to 0.13.

2021-04-12 18:07 UTC, giarc3 commented on CHANGELOG.md
> +## 0.12.1 (Unreleased)
Good catch

2021-04-12 22:53 UTC, merged